package com.example.szakdolgozat

object GameConstants {

    val words = listOf(
        "muflon",
        "nyest",
        "vaddisznó",
        "mosómedve",
        "házi/görény",
        "mezei/nyúl",
        "gímszarvas",
        "pézsmapocok",
        "aranysakál",
        "dámszarvas",
        "üregi/nyúl",
        "róka",
        "kősüllő",
        "harcsa",
        "csuka",
        "busa",
        "kárász",
        "törpeharcsa",
        "ponty",
        "balin",
        "vörösszárnyú/keszeg",
        "sügér",
        "naphal",
        "fogassüllő",
        "menyhal",
        "compó",
        "amur",
        "Cseszneki/vár",
        "Béke/sztúpa",
        "Szépkilátó",
        "Kőtenger",
        "Szent/Mihály/kápolna",
        "Salföldi/Major",
        "Hegyestű",
        "tavasbarlang",
        "Szigligeti/vár",
        "Csobánc/vára",
        "Tihanyi/Bencés/Apátság",
        "Hévíz",
        "bakcsó",
        "búbos/vöcsök",
        "kis/kócsag",
        "nyári/lúd",
        "nagy/kócsag",
        "dankasirály",
        "bütykös/hattyú",
        "üstökösgém",
        "fattyúszerkő",
        "szürke/gém",
        "fehérszárnyú/szerkő",
        "guvat",
        "jégmadár",
        "barna/rétihéja",
        "rétisas",
        "üstökös/réce",
        "kárókatona",
        "kis/vöcsök",
        "Balaton"

    )

}